### ISSUE TITLE
Can't create Pangolin block

### ISSUE THREAD

**Issue by Ric92** [Bardo91/mico#70]
Typical core dumped error 

Flow: https://github.com/Bardo91/flow/commit/807747c9ff3bda24ff232cccf81abfdd1f4b82ab
nodeeditor: https://github.com/Bardo91/nodeeditor/commit/82e57e5e81fe74b2e60c980fccaf4454b1867936

**Comment by Bardo91** [comment]
mico: https://github.com/Bardo91/mico/commit/3556687e23db7415861f8ce90ff13934ad4505e2

**Comment by Bardo91** [comment]
Quick fix in MICO: d48f77950ace2801e615a3e3d1b0ce5233b3b7fa

Tested with:
* Flow: Bardo91/flow@807747c
* nodeeditor: Bardo91/nodeeditor@82e57e5
